<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
	<AssemblyName>AIOLauncher</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<PublishSingleFile>true</PublishSingleFile>
	<IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<ApplicationIcon>logo.ico</ApplicationIcon>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<PlatformTarget>x64</PlatformTarget>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Subphim\ExportDebugger.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fonts\RussoOne-Regular.ttf" />
    <None Remove="icon.ico" />
    <None Remove="Resources\apps.png" />
    <None Remove="Resources\back.png" />
    <None Remove="Resources\capcut.png" />
    <None Remove="Resources\dashboard.png" />
    <None Remove="Resources\dich.png" />
    <None Remove="Resources\edit.png" />
    <None Remove="Resources\jianying.png" />
    <None Remove="Resources\loading.gif" />
    <None Remove="Resources\logo.png" />
    <None Remove="Resources\logo1.png" />
    <None Remove="Resources\ocr.png" />
    <None Remove="Resources\phim.png" />
    <None Remove="Resources\TTS.png" />
    <None Remove="Resources\video.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ColorPickerWPF" Version="1.0.9" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="Eziriz.Reactor.TrimHelper" Version="6.9.0" />
    <PackageReference Include="FFME.Windows" Version="4.4.350" />
    <PackageReference Include="FFmpeg.AutoGen" Version="4.4.0" />
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3783" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3405.78" />
    <PackageReference Include="Mpv.NET" Version="1.2.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="NAudio.Extras" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
    <PackageReference Include="SharpCompress" Version="0.40.0" />
    <PackageReference Include="SoundTouch.Net" Version="2.3.2" />
    <PackageReference Include="System.Management" Version="9.0.7" />
    <PackageReference Include="System.Windows.Forms.Ribbon35" Version="3.5.8" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.6" />
    <PackageReference Include="WPF-UI" Version="4.0.3" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="7z.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="7z.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ffplay.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Fake Ngọc Huyền.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Giọng đọc thơ.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Hoa.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Hương Giang.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Hương Tràm.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Lan Anh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\MC Hương Ngọc.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\MC Nam Minh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\MC Ngọc Trinh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\MC Đám Ma.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Nam Minh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Nam Miền Nam 2.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Nam Miền Nam.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Nam Trầm.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Ngọc Diễm.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Ngọc Diệp.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Ngọc Nhi.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Podcast 2.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Podcast.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Quang Hùng.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Quang Hải.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Quang Minh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Quang Toản.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Quỳnh Anh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Quỳnh Như.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Thiền Anh.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Thành Tiến.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Trung Thường.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Trầm Giọng Bắc.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\voices\Văn Hoàng.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\SoundTouch.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x86\native\SoundTouch.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="TTS.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Webcontent\MovieBrowser.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Webcontent\scripts.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Webcontent\styles.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Player.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\RussoOne-Regular.ttf" />
    <Resource Include="Resources\apps.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\back.png" />
    <Resource Include="Resources\capcut.png" />
    <Resource Include="Resources\dashboard.png" />
    <Resource Include="Resources\dich.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\edit.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\jianying.png" />
    <Resource Include="Resources\loading.gif">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\ocr.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\phim.png" />
    <Resource Include="Resources\TTS.png" />
    <Resource Include="Resources\video.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <None Update="*.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
